## Task 1

The NorthWind data set, provided in XML format on Moodle, includes details of orders received by a fictitious business and is based on a sample Microsoft SQL Server database.

- (a)	Create a function to import this XML file. Your function must include all appropriate exception handling clauses covering all possible error conditions. The function should return the parsed contents of the XML file.

In [69]:
import xml.etree.ElementTree as ET

# XML File path 
filepath = "NorthWind.xml"

def read_xml_file(filepath):
    """
    Reads an XML file from the given filepath and parses it.
    
    Input : file_path , type : str
    Return : xmltree , type : object

    """
    try :
        # Read xml file
        xmldata = open(filepath,'r')
        xmltree = ET.fromstring(xmldata.read())
        return xmltree
    except FileNotFoundError:
        print(f'File not found. Please check the file path :{filepath}')
    except IOError:
        print(f'An error occurred while trying to read the file: {filepath}\nError: {e}')
    finally :
        xmldata.close()  

parsed_xml = read_xml_file(filepath)

- (b)	Using the function you created in a) above, load the XML file, assigning the parsed contents to a variable named parsed_xml. Then use the print() function to display the OrderID, CustomerID, ShipCity and ShipCountry for the 10th, 13th, 16th and 19th orders. Hint: the range() function might come in useful here!

In [23]:
def get_data(values, xmltree):
    """
    Reads an the data from XML file and return the data.
    
    Input : values , type : list
    Return : xmltree , type : object

    """

    data = [ ]
    for i in values :
            OrderID = xmltree[0][i].get('OrderID')
            CustomerID = xmltree[0][i].find("CustomerID").text
            ShipCity = xmltree[0][i].find('ShipCity').text
            ShipCountry = xmltree[0][i].find("ShipCountry").text
            data.append( {
                "OrderID" : OrderID,
                "CustomerID" : CustomerID,
                "ShipCity" : ShipCity,
                "ShipCountry" : ShipCountry
            })
    return data
values = [10,13,16,19]
get_data_result = get_data(values, parsed_xml)

In [26]:
get_data_result
# print(get_data_result)

[{'OrderID': '10258',
  'CustomerID': 'ERNSH',
  'ShipCity': 'Graz',
  'ShipCountry': 'Austria'},
 {'OrderID': '10261',
  'CustomerID': 'QUEDE',
  'ShipCity': 'Rio de Janeiro',
  'ShipCountry': 'Brazil'},
 {'OrderID': '10264',
  'CustomerID': 'FOLKO',
  'ShipCity': 'Bräcke',
  'ShipCountry': 'Sweden'},
 {'OrderID': '10267',
  'CustomerID': 'FRANK',
  'ShipCity': 'München',
  'ShipCountry': 'Germany'}]

- (c)	Using the parsed contents of the XML file in the parsed_xml variable created earlier, find all orders taken by EmployeeID 5. Export all orders and their associated order details data for these orders to a CSV file. Your CSV file should contain field names, using the tag names in the XML file. Note: you should not use Pandas for this task.

In [82]:
def get_child(parsed_xml):
    for root in parsed_xml:
            for child in root :
                if child.find("EmployeeID").text == "5":
                    return child
            
            
            
def get_cond_data(child):
    data = [ ]
    for grandchild in child:
        if grandchild.tag == "OrderDetails":
            for element in grandchild:
                    ProductID = element.find("ProductID").text
                    UnitPrice = element.find("UnitPrice").text
                    Quantity = element.find("Quantity").text
                    Discount = element.find("Discount").text
                    data.append( {
                            "ProductID" : ProductID,
                            "UnitPrice" : UnitPrice,
                            "Quantity" : Quantity,
                            "Discount" : Discount
                        })
    return data

child = get_child(parsed_xml)
get_data_result = get_cond_data(child)

In [83]:
get_data_result

[{'ProductID': '11',
  'UnitPrice': '14.0000',
  'Quantity': '12',
  'Discount': '0'},
 {'ProductID': '42', 'UnitPrice': '9.8000', 'Quantity': '10', 'Discount': '0'},
 {'ProductID': '72', 'UnitPrice': '34.8000', 'Quantity': '5', 'Discount': '0'}]

In [84]:
import csv

# CSV File Path
file_path = "./Orderdetails.csv"

def write_to_csv(filepath, data):
    """
    Writes the data to CSV File
    
    Input: CSV File Path, type : str
           Data , type : list

    Return : NA 
    """
    try :
        # Writing to CSV File
        my_csv = open(file_path, 'w')
        # Creating a CSV Writer Object
        csvwriter = csv.writer(my_csv)
        head = [ "ProductID" , "UnitPrice" , "Quantity" , "Discount" ] # Specify Column Names here
        # Writing Columns to the file
        csvwriter.writerow(head)

        for i in range(len(data)):
            row = [ ]
            #Specify the names of Keys of the data such as "Name","Gender"
            row.append(data[i]['ProductID'])
            row.append(data[i]['UnitPrice'])
            row.append(data[i]['Quantity'])
            row.append(data[i]['Discount'])
            # Writing Rows to the File
            csvwriter.writerow(row)

    except FileNotFoundError:
        print(f'File not found. Please check the file path :{filepath}')
    except IOError:
        print(f'An error occurred while trying to read the file: {filepath}\nError: {e}')
    finally :
        my_csv.close()
        
write_to_csv(filepath,get_data_result)

## Task 2

In [86]:
import numpy as np

- (a)	Create a three dimensional NumPy ndarray containing all even numbers between 1000 and 8998. The resulting ndarray should be assigned to a variable named array_a and should be reshaped to have 8 layers, 50 rows and 10 columns.

In [104]:
array_a = np.arange(999,8998,2)

In [105]:
a = array_a.reshape(8,50,10)

In [122]:
data = [ ]
for i in range(0,3):
    data.append(a[3][-1])



In [123]:
data

[array([4979, 4981, 4983, 4985, 4987, 4989, 4991, 4993, 4995, 4997]),
 array([4979, 4981, 4983, 4985, 4987, 4989, 4991, 4993, 4995, 4997]),
 array([4979, 4981, 4983, 4985, 4987, 4989, 4991, 4993, 4995, 4997])]

- (b) Compute the mean of the values in each of the last 3 rows in the 4th layer. The result should be a 1D array with 3 separate values

In [124]:
Mean = [ ]
for i in range(0,3):
    mean = np.mean(data[i])
    Mean.append(mean)

In [125]:
Mean

[4988.0, 4988.0, 4988.0]

In [127]:
# for i in range(0,8):
#     data.append(a[i][i][4])

- (c)	Compute the product of all cells in the first 4 columns in all layers. The result should be a single scalar value.

In [132]:
result = a[:, :, :4]

In [133]:
product_result = np.prod(result)
product_result

2009114881

- (d)	Using a single NumPy function, split the 3D array created in a) above column-wise, producing five separate arrays

In [ ]:
np.hsplit(a, 5)

- (e)	Create two new ndarrays each containing 15 values. The first should be named array_b and should have evenly spaced values from 60 to 75. The second should be named array_c and should contain evenly spaced values from 8 to 40. Multiply the corresponding array entry values from each of the two arrays, i.e. perform the multiplication element-wise.

In [146]:
array_b = np.arange(60,75)
array_c = np.arange(8,38,2)

print(array_b)
print(array_c)

product = array_b * array_c
product

[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]
[ 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36]


array([ 480,  610,  744,  882, 1024, 1170, 1320, 1474, 1632, 1794, 1960,
       2130, 2304, 2482, 2664])

## Task 3

Write a function that has one parameter that takes a string value as its argument. The function should use a regular expression to check if the string passed as an argument contains a valid email address. The function should return the number of valid email addresses found.
Test your function with multiple sample strings containing both valid and invalid email addresses. An example of an invalid email address would be user@server@domain.com (an email address can contain only one @)


In [182]:
import re

def check_email_address(sample_string):
    
    count = 0
    
    pattern_for_email = r'\b[A-Za-z0-9._%+-]+[@A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
    
    emails = re.findall(pattern_for_email, sample_string)
    print(emails)
    
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
    
    for email in emails:
        if re.match(email_pattern,email):
            count = count + 1 
    
    return count

sample_string = "Get in touch with student_support@nci.com for assistance exa@mple@gmail..com "

count = check_email_address(sample_string)
count
    

['student_support@nci.com', 'exa@mple@gmail..com']


1