## Task 1|

In [30]:
import xml.etree.ElementTree as ET
import csv


In [31]:
xmldata = open("Titanic.xml",'r')
xmltree = ET.fromstring(xmldata.read())

values = [ 2 , 4 , 8, 16 , 32]

data = [ ]
for i in values :
        Name = xmltree[i].find('Name').text
        Sex = xmltree[i].find("Sex").text
        data.append( {
            "Name" : Name,
            "Gender" : Sex   
        })

In [37]:
file_path = "./Titanic.csv"

try :
    my_csv = open(file_path, 'w')
    csvwriter = csv.writer(my_csv)
    head = ["Name", "Gender"]
    csvwriter.writerow(head)
    
    for i in range(len(data)):
        row = [ ]
        row.append(data[i]["Name"])
        row.append(data[i]["Gender"])
        csvwriter.writerow(row)
        
except FileNotFoundError:
    print('Could not open the file:'.format(file_path))
except IOError:
    print('Could not write to the file:'.format(file_path))
finally :
    my_csv.close()

In [39]:
data = [ ]
for child in root:
    if child.find('Age').text is not None and float(child.find('Age').text) < 30.0 and child.find('Pclass').text in ['1','2']:
        Name = child.find('Name').text
        Sex = child.find("Sex").text
        Cabin = child.find("Cabin").text
        Ticket = child.find("Ticket").text
        PassengerId = child.find("PassengerId").text
        data.append( {
            "Name" : Name,
            "Gender" : Sex,
            "Cabin" : Cabin,
            "Ticket" : Ticket,
            "PassengerId" : PassengerId,
        })


In [40]:
file_path = "./Titanic.csv"

try :
    my_csv = open(file_path, 'w')
    csvwriter = csv.writer(my_csv)
    head = ["Name", "Gender" , "Cabin", "Ticket", "PassengerId" ]
    csvwriter.writerow(head) 
    for i in range(len(data)):
        row = [ ]
        row.append(data[i]["Name"])
        row.append(data[i]["Gender"])
        row.append(data[i]["Cabin"])
        row.append(data[i]["Ticket"])
        row.append(data[i]["PassengerId"])
        csvwriter.writerow(row)
except FileNotFoundError:
    print('Could not open the file:'.format(file_path))
except IOError:
    print('Could not write to the file:'.format(file_path))
finally :
    my_csv.close()

In [29]:
import csv

csv_file = "./Passenger.csv"

try :
    
    theo_csv = open(csv_file, 'w')
    csvwriter = csv.writer(theo_csv)
    head = ["Name", "Gender" , "Cabin", "Ticket", "PassengerId" ]
    csvwriter.writerow(head)
    
    for i in range(len(data)):
        row = [ ]
    
        csvwriter.writerow(row)
except FileNotFoundError:
    print('Could not open the file:'.format(csv_file))
except IOError:
    print('Could not write to the file:'.format(csv_file))
finally :
    theo_csv.close()

## Task 2

In [2]:
import numpy as np

In [3]:
x = np.arange(1,28)

In [4]:
matrix1 = x.reshape(3,3,3)

In [5]:
matrix1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [6]:
data = [[[9, 8, 7], [6, 5, 4], [3, 2, 1]],
        [[27, 26, 25], [24, 23, 22], [21, 20, 19]],
        [[18, 17, 16], [15, 14, 13], [12, 11, 10]]]

matrix2 = np.array(data)



In [7]:
matrix2

array([[[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]],

       [[27, 26, 25],
        [24, 23, 22],
        [21, 20, 19]],

       [[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]]])

In [8]:
"""
1. Extract the diagonal from the each dimension of each matrix.

"""
diagonal1 = np.diagonal(matrix1, axis1=1, axis2=2)  # 1st main diagonal  
diagonal2 = np.diagonal(matrix2, axis1=1, axis2=2)  # 1st main diagonal  

diagonals_1 = np.array([diagonal1])
diagonals_2 = np.array([diagonal2])

In [9]:
diagonals_1


array([[[ 1,  5,  9],
        [10, 14, 18],
        [19, 23, 27]]])

In [10]:
diagonals_2

array([[[ 9,  5,  1],
        [27, 23, 19],
        [18, 14, 10]]])

In [11]:
"""
2. Take sum of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D 
matrix. [10 marks]
"""
result = diagonals_1 + diagonals_2
result

array([[[10, 10, 10],
        [37, 37, 37],
        [37, 37, 37]]])

In [12]:
"""
(b) Take product of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D matrix.

"""

product = diagonals_1 * diagonals_2

product

array([[[  9,  25,   9],
        [270, 322, 342],
        [342, 322, 270]]])

In [13]:
"""
(c) Calculate the sum of all the elements in the resulting product.

"""
result = np.sum(product)
result

1911

In [16]:
"""
Calculate the variance of the values in the flattened (1D) version of the matrices. Hint use Numpy var 
function [10 marks]
"""

m1 = np.ravel(matrix1 , order = 'c')
m2 = np.ravel(matrix2 , order = 'c')

In [17]:
print("Variance (Matrix 1) : ", np.var(m1))
print("Variance (Matrix 2) : ", np.var(m2))

Variance (Matrix 1) :  60.666666666666664
Variance (Matrix 2) :  60.666666666666664


In [29]:
"""
(e) Create two new ndarrays each containing 10 values. The first should have evenly spaced values from 20 
to 60. The second should contain evenly spaced values from 10 to 30. Add together corresponding array 
entry values from each of the two arrays, i.e. perform the addition element-wise. [5 marks]

"""

array_1 = np.arange(20,60,4)
array_2 = np.arange(10,30,2)

result = array_1 + array_2

result

array([30, 36, 42, 48, 54, 60, 66, 72, 78, 84])

## Task 3 (20 marks)


In [ ]:
import re

def is_valid_class_c_ipv4_address(ip_str):
    # Define a regular expression pattern for Class C IPv4 address
    pattern = r'^(19[2-9]|2[01][0-9]|22[0-3])\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'

    # Use re.match to check if the string matches the pattern
    if re.match(pattern, ip_str):
        return True
    else:
        return False

# Test the function
ip_address = "192.168.1.1"
if is_valid_class_c_ipv4_address(ip_address):
    print(f"{ip_address} is a valid Class C IPv4 address")
else:
    print(f"{ip_address} is not a valid Class C IPv4 address")
