In [ ]:
# Excpetion Handling
"""
a) Create a text file and manually add some data to the file

"""
try :
    sample = open("Sample.txt","a")
except FileNotFoundError as e :
    print(f" Error : {e}")
except FileExistsError as e :
    print(f" Error : {e}")
else :
    value = "Hello World"
    sample.write(value)
finally :
    sample.close()

"""
b) Write Python code to
• open the file for write only access
• attempt to read the contents of the file

"""

file = open('Sample.txt', 'w')
try :
    file.read()
except IOError as e : 
    print(f"Error : {e}")
except Exception as e:
    print(f"Exception : {e}")
finally :
    file.close()





### Custom Exception

In [1]:
class CustomException(Exception):
    "Raises a Custom Exception"
    pass


In [1]:
"""
2. Numpy Exercise A
a) Create an array with the arange function and reshape the array as follows:
b = arange(24).reshape(2,3,4)
This gives us a 3-dimensional data structure – you can think of it as being like 2
spreadsheet sheets where each sheet contains 3 rows of data and each row
contains 4 columns.

"""

import numpy as np

a = np.arange(24)
a = a.reshape(2,3,4)

In [2]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
"""
Using indexing and slicing perform the following tasks:
i) Choose the first set of 3 rows and 4 columns of data
"""
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
"""
ii) Choose the second row of data from the second set of 3 rows of data

"""

a[1][1]

array([16, 17, 18, 19])

In [5]:
"""
iii) Choose all the data from the second column for both the first and second
sets of rows and columns of data
"""

for i in range(0,2):
    for j in range(len(a[0])):
        print(a[i][j][1])
        

1
5
9
13
17
21


In [6]:
"""
b) Use the ravel function to flatten the data. What’s the difference between ravel
and flatten?
"""

a = np.ravel(a , order = 'c')

In [38]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
"""
c) Reshape the data so that there are 6 rows of 4 columns per row.

"""
at = a.reshape(6,4)

In [13]:
"""
d) Get the transpose of the new data structure.

"""

np.transpose(at)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [14]:
"""
e) Restack the rows of the transposed data structure in reverse order (hint: look at
the row_stack function).
"""



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
reversed_array = np.row_stack(reversed(at))

C:\Users\smula\AppData\Local\Temp\ipykernel_3256\2886686844.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  reversed_array = np.row_stack(reversed(at))


In [16]:
reversed_array

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [17]:
"""
f) Split the resulting data structure horizontally (hint: look at the hsplit function).
"""

splited_array = np.hsplit(reversed_array, 2)

In [18]:
splited_array

[array([[20, 21],
        [16, 17],
        [12, 13],
        [ 8,  9],
        [ 4,  5],
        [ 0,  1]]),
 array([[22, 23],
        [18, 19],
        [14, 15],
        [10, 11],
        [ 6,  7],
        [ 2,  3]])]

### 3. NumPy Exercise B

- NOTE:
* The AAPL.csv contains some stock price data for Apple.
* The MSFT.csv contains some stock price data for Microsoft.

In [33]:
"""
a) Use the loadtxt command to load data from AAPL.csv from columns 5 and 7 (i.e.,
the close price and the volume)
"""
close, volume = np.loadtxt('AAPL.csv', delimiter=',', usecols=(4,6), unpack=True, skiprows = 1)

In [36]:
"""
b) Based on the data provided, calculate the volume weighted average price for the
stock (i.e., calculate the average price using the volume as weight values).
"""
vwap = np.average(close, weights = volume)

In [37]:
vwap

190.02952578964312

In [44]:
"""
c) Calculate the median value of the closing prices (hint: use the median function).

"""

median = np.median(close)
median

197.0

In [45]:
"""
d) Calculate the variance value of the closing prices.

"""

variance = np.var(close)
variance

432.8804568188714

In [48]:
"""
e) Again, use the loadtxt command to load data from columns 3 and 4 (i.e., the high
prices and the low prices).
"""
High , Low = np.loadtxt('AAPL.csv', delimiter = ',', usecols=(2,3), unpack=True, skiprows = 1)

In [53]:
"""
f) Use the max and min functions to get the highest high and the lowest low value.

"""
highest = np.max(High)
lowest = np.min(Low)

print("Highest of High : ", highest)
print("Lowest of Low : ", lowest)

Highest of High :  229.929993
Lowest of Low :  142.0


In [54]:
"""
g) Load data from column 5 of AAPL.csv. Also, load data from column 5 of MSFT.csv.

"""
close_AAPL = np.loadtxt('AAPL.csv', delimiter=',', usecols=(4), unpack=True, skiprows = 1)
close_MSFT = np.loadtxt('MSFT.csv', delimiter=',', usecols=(4), unpack=True, skiprows = 1)

In [57]:
"""
h) Calculate the covariance matrix of the closing prices of AAPL and MSFT (hint: use
the cov function).
"""
cov_mat = np.stack((close_AAPL, close_MSFT), axis = 0) 
covv = np.cov(cov_mat)

In [58]:
# i) View the values on the diagonal (hint: diagonal).
np.diag(covv)

array([434.60508015, 184.73421932])

In [60]:
"""
j) Calculate the correlation coefficient of the closing prices of AAPL and MSFT (hint:
corrcoef).
"""

corr = np.corrcoef(close_AAPL,close_MSFT)
corr

array([[1.        , 0.65988802],
       [0.65988802, 1.        ]])

In [62]:
# Write a Python program that will identify URLs using regular expressions.


import re

# Sample text containing URLs
text = """
Visit our website at https://www.example.com for more information.
You can also find us at http://www.another-example.com.
For secure connections, use https://secure-example.com.
"""

# Regular expression pattern to match URLs
url_pattern = r'https?://\S+'

# Find all URLs in the text
urls = re.findall(url_pattern, text)

# Print the URLs
for url in urls:
    print(url)


https://www.example.com
http://www.another-example.com.
https://secure-example.com.


In [64]:
pip install nltk

     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
     - -------------------------------------- 0.1/1.5 MB 1.3 MB/s eta 0:00:02
     ------ --------------------------------- 0.2/1.5 MB 2.4 MB/s eta 0:00:01
     --------- ------------------------------ 0.4/1.5 MB 2.5 MB/s eta 0:00:01
     ----------------- ---------------------- 0.7/1.5 MB 3.8 MB/s eta 0:00:01
     ------------------------------ --------- 1.1/1.5 MB 5.6 MB/s eta 0:00:01
     ---------------------------------------- 1.5/1.5 MB 6.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 42.0/42.0 kB 2.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ---------------------------------------- 57.6/57.6 kB ? eta 0:00:00
   ---------------------------------------- 0.0/269.6 kB ? eta -:--:--
   --------------------------------------- 269.6/269.6 kB 16.2 MB/s eta 0:00:00
   ----------

In [1]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True